### ISSUE TITLE
Add documentation for git

### ISSUE THREAD

**Issue by sjmog** [dawi118/pokemon_battle#6]
Add a subdirectory called `docs`.
Inside `docs`, add files for `git_workflow.md`, `git_remotes.md` and `git_model.md`.
Inside each file, summarise the git model.

**Comment by sjmog** [comment]
List of commands so far:

```
.
..
echo
touch
mkdir
ln
ls
clear
brew
tree
cd
subl
```

**Comment by dawi118** [comment]
Added docs sub-directory including information on:

1. Git Model
2. Git Workflow
3. Git Remotes

Readme updated with explanations of several commands.

Accidental creation of doc folder. 

Deletion of .DS_Store & creation of .gitignore w/ DS_Store in.
